name: Update Filecoin Plus registry

# Support for configurable cron scheduling and manual workflow dispatch.
on:
  # Manually run the workflow
  workflow_dispatch:
  schedule:
    # Automatically run the workflow every night at midnight
    - cron: '0 0 * * *'

jobs:
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Set environment variables and run the script
        run: |
          npm run start
        env:
          REPO_OWNER: ${{ vars.BOT_REPOSITORY_ORG }}
          REPO_NAME: ${{ vars.BOT_REPOSITORY_NAME }}
          REPO_PATH: ${{ vars.BOT_REPOSITORY_PATH }}
          REPO_BRANCH: ${{ vars.BOT_REPOSITORY_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LOTUS_TOKEN: ${{ secrets.LOTUS_TOKEN }}
