name: Update Filecoin Plus registry

# Support for configurable cron scheduling and manual workflow dispatch.
on:
  # Manually run the workflow
  workflow_dispatch:
  schedule:
    # Automatically run the workflow every hour
    - cron: '0 * * * *'

jobs:
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Set environment variables and run the script
        run: |
          export REPO_OWNER=${{ env.BOT_REPOSITORY_ORG }}
          export REPO_NAME=${{ env.BOT_REPOSITORY_NAME }}
          export REPO_PATH=${{ env.BOT_REPOSITORY_PATH }}
          export REPO_BRANCH=${{ env.BOT_REPOSITORY_BRANCH }}
          npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LOTUS_TOKEN: ${{ secrets.LOTUS_TOKEN }}
